#server
server:
  port: 8000
spring:
  profiles:
    active: dev
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: rose-gateway-server
  zipkin:
    base-url: http://127.0.0.1:9411/
    discoveryClientEnabled: false
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.addr}
        namespace: ${nacos.namespace}
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现组件找到其他的微服务
          enabled: false
      httpclient:
        connect-timeout: 45000
        response-timeout: 45000
      routes:
        - id: rose-content-server-a-route
          uri: lb://rose-content-server-a
          predicates:
            - Path=/rose-content-server-a/**
        - id: rose-content-server-b-route
          uri: lb://rose-content-server-b
          predicates:
            - Path=/rose-content-server-b/**
        - id: rose-login-server-route
          uri: lb://rose-login-server
          predicates:
            - Path=/rose-login-server/**
          filters:
            - name: RequestRateLimiter
              args:
                # 令牌桶每秒填充平均速率
                redis-rate-limiter.replenishRate: 2
                # 令牌桶的上限
                redis-rate-limiter.burstCapacity: 2
                # 使用SpEL表达式从Spring容器中获取Bean对象
                key-resolver: "#{@pathKeyResolver}"
  redis:
    host: ${redis.set.host}
    port: ${redis.set.port}
    database: ${redis.set.database}
    password: ${redis.set.password}
logging:
# 嫌日志太多就注掉
#  level:
#    org.springframework.cloud.gateway: trace
  config: classpath:logback.xml